name: Build for linux

on: [push, pull_request]

jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Cache openal
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: libopenal-dev
          version: 0.0.1
          execute_install_scripts: true
          
      - name: Install sndfile
        run: sudo apt install -y libsndfile-dev libx11-dev

      - name: Compile all the binaries
        run: make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: bin/**
