name: Build for linux

on: [push, pull_request]

jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo code
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Cache openal
        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: libopenal-dev
          version: 0.0.1
          execute_install_scripts: true
      - name: Install sndfile
        run: sudo apt install libsndfile-dev
          
      # Compile the code itself
      - name: Compile the binaries
        run: make all

      # Upload the bin folder
      - uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: bin/**

  build-for-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get cached audio libs
        id: cache-audio
        uses: actions/cache@v4
        env:
          cache-name: cache-windows-audio
        with:
          path: |
            lib\
            include\
          key: ${{ env.cache-name }}-build-0
      - name: Install audio dependencies
        if: steps.cache-audio.outputs.cache-hit != 'true'
        run: |
           C:\msys64\usr\bin\wget.exe https://github.com/libsndfile/libsndfile/releases/download/1.2.2/libsndfile-1.2.2-win64.zip -O sndfile.zip
           C:\msys64\usr\bin\wget.exe https://github.com/kcat/openal-soft/releases/download/1.23.1/openal-soft-1.23.1-bin.zip     -O openal.zip
           7z x sndfile.zip
           7z x openal.zip

           md lib
           md include
           md include\AL

           copy libsndfile-1.2.2-win64\bin\sndfile.dll lib\sndfile.dll
           copy libsndfile-1.2.2-win64\lib\sndfile.lib lib\sndfile.lib
           copy libsndfile-1.2.2-win64\include\sndfile.h include\sndfile.h

           copy openal-soft-1.23.1-bin\bin\Win64\soft_oal.dll lib\openal.dll
           copy openal-soft-1.23.1-bin\libs\Win64\OpenAL32.lib lib\openal.lib
           copy openal-soft-1.23.1-bin\include\AL\*.h include\AL\

           dir
      - name: Compile the binaries
        run: |
          .\engine\build.cmd
          clang++ -Wno-everything -Ofast -shared bin\o\types.obj bin\o\logging.obj game/audio.cc -o bin/scripts/audio.dll -I./include/ -L./lib/ -lopenal -lsndfile

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: bin/**
