name: Build for linux

on: [push, pull_request]

jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt install libopenal-dev libsndfile-dev
        
      - name: Run make
        run: |
          make all
          make -C utilities/blender_ext
          cp utilities/blender_ext/scene_extension.zip bin/

      # Upload the bin folder
      - uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: bin/**
  build-for-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run make
        run: |
          make all
          make -C utilities/blender_ext
          xcopy utilities/blender_ext/scene_extension.zip bin/

      - uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: bin/**