name: Build and Release

on:
  push: {}  # This triggers the workflow on any push event

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # Build on Ubuntu with Clang available
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Run make
        run: |
          sudo apt update
          sudo apt install libopenal-dev libsndfile-dev
          make
        
      - uses: actions/upload-artifact@v3
        with:
          name: built-artifacts
          path: bin/**

