name: Build and Release

on:
  push: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the repository code

      - name: Run make
        run: |
          sudo apt install libopenal-dev libsndfile-dev
          make build utils
        
      - uses: actions/upload-artifact@v3
        with:
          name: built-artifacts
          path: bin/**

