name: Build

on: [push, pull_request]

jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt install libopenal-dev libsndfile-dev
        
      - name: Run make
        run: make all

      # Upload the bin folder
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: bin/**
          
  build-blender-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run make
        run: make -C utilities/blender_ext
      - uses: actions/upload-artifact@v4
        with:
          name: blender-extension
          path: utilities/blender_ext/scene_extension.zip

  build-for-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run make
        run: |
          .\build.cmd

      - uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: bin/**