name: Build

on: [push, pull_request]

jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt install libopenal-dev libsndfile-dev
        
      - name: Run make
        run: make all

      # Upload the bin folder
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: bin/**
          
  build-blender-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run make
        run: make -C utilities/blender_ext
      - uses: actions/upload-artifact@v4
        with:
          name: blender-extension
          path: utilities/blender_ext/scene_extension.zip

  build-for-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get cached audio libs
        id: cache-step
        uses: actions/cache@v4
        env:
          cache-name: cache-windows-audio
        with:
          path: pre-cached\
          key: ${{ env.cache-name }}-build-0
          
      - name: Install audio dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: |
           mkdir D:\audio
           mkdir D:\audio\openal
           mkdir D:\audio\sndfile

           mkdir pre-cached
           mkdir pre-cached\includes
           mkdir pre-cached\dlls
           
           C:\msys64\usr\bin\wget.exe https://github.com/libsndfile/libsndfile/releases/download/1.2.2/libsndfile-1.2.2-win64.zip -O D:\audio\sndfile.zip
           C:\msys64\usr\bin\wget.exe https://github.com/kcat/openal-soft/releases/download/1.23.1/openal-soft-1.23.1-bin.zip     -O D:\audio\openal.zip
           7z x D:\audio\sndfile.zip -oD:\audio\sndfile
           7z x D:\audio\openal.zip  -oD:\audio\openal
           copy D:\audio\sndfile\bin\*.*               pre-cached\dlls\
           copy D:\audio\openal\bin\Win64\soft_oal.dll pre-cached\dlls\
           copy D:\audio\sndfile\include\*.*           pre-cached\includes\
           copy D:\audio\openal\include\*              pre-cached\includes\

      - name: Compile the binaries
        run: .\build.cmd

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: bin/**