name: Build for linux

on: [push, pull_request]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt install libopenal-dev libsndfile-dev
        
      - name: Compile the binaries
        run: make all

      # Upload the bin folder
      - uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: bin/**

